#!/usr/bin/env bash

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This code is for PoC environment only.
# This demo code is not built for production workload.

# =============================================================================
# template/deploy_agent.sh
#
# Template deploy script for a new team's agent.
# Copy this to your project root and customize AGENT_DIR and AGENT_NAME.
#
# Usage:
#   source agent.env          # generated by: bash scripts/generate_agent_config.sh
#   bash deploy_agent.sh
#
# Prerequisites:
#   1. terraform apply complete (infra provisioned)
#   2. agent.env generated (bash scripts/generate_agent_config.sh)
#   3. agents/my-agent/requirements.txt updated with AR_PYTHON_INDEX
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ── Configure these for your agent ──────────────────────────────────────────
AGENT_DIR="${SCRIPT_DIR}/agents/my-agent"        # path to your agent directory
AGENT_NAME="${AGENT_DISPLAY_NAME:-my-agent-v1}"  # RE display name (from env or default)
# ────────────────────────────────────────────────────────────────────────────

# Validate required env vars (set by sourcing agent.env)
for var in GOOGLE_CLOUD_PROJECT GOOGLE_CLOUD_LOCATION AGENT_GATEWAY_INGRESS AGENT_GATEWAY_EGRESS; do
  if [[ -z "${!var:-}" ]]; then
    echo "❌ Missing required env var: $var"
    echo "   Run: source agent.env   (generate with: bash scripts/generate_agent_config.sh)"
    exit 1
  fi
done

echo "╔══════════════════════════════════════════════════════════╗"
echo "║              Agent Deploy — Agent Gateway                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo "  Agent      : $AGENT_NAME"
echo "  Project    : $GOOGLE_CLOUD_PROJECT"
echo "  Region     : $GOOGLE_CLOUD_LOCATION"
echo "  Ingress GW : $AGENT_GATEWAY_INGRESS"
echo "  Egress GW  : $AGENT_GATEWAY_EGRESS"
echo ""

# ── Set up virtualenv ────────────────────────────────────────────────────────
VENV="${SCRIPT_DIR}/.venv"
if [[ ! -x "${VENV}/bin/python" ]]; then
  echo "▶ Creating virtualenv..."
  python3 -m venv "$VENV"
fi

echo "▶ Installing SDK (pinned versions)..."
"${VENV}/bin/pip" install -q \
  "google-adk==${GOOGLE_ADK_VERSION:-1.31.1}" \
  "google-cloud-aiplatform[adk,agent_engines]==${GOOGLE_CLOUD_AIPLATFORM_VERSION:-1.149.0}"

echo "▶ Installing agent requirements..."
"${VENV}/bin/pip" install -q \
  --extra-index-url "${AR_PYTHON_INDEX}" \
  -r "${AGENT_DIR}/requirements.txt"

# ── Apply the gateway .pth patch ─────────────────────────────────────────────
# This injects agentGatewayConfig into the adk deploy call so the RE
# is created with gateway binding. Without this patch, gateway enforcement
# is disabled even if the infra is deployed.
PATCH_SCRIPT="${SCRIPT_DIR}/scripts/patch_sdk_for_rest_create.py"
if [[ ! -f "$PATCH_SCRIPT" ]]; then
  # Fetch from the foundation repo if not present locally
  echo "⚠️  patch_sdk_for_rest_create.py not found locally."
  echo "   Copy it from: https://github.com/your-org/mod-agw-foundation/scripts/"
  exit 1
fi

echo "▶ Applying Agent Gateway .pth patch..."
"${VENV}/bin/python" "$PATCH_SCRIPT" \
  --ingress "$AGENT_GATEWAY_INGRESS" \
  --egress  "$AGENT_GATEWAY_EGRESS" \
  --venv    "$VENV"

# ── Deploy ───────────────────────────────────────────────────────────────────
echo "▶ Deploying Reasoning Engine: $AGENT_NAME..."
cd "$AGENT_DIR"
"${VENV}/bin/adk" deploy agent_engine \
  --project="${GOOGLE_CLOUD_PROJECT}" \
  --region="${GOOGLE_CLOUD_LOCATION}" \
  --display_name="${AGENT_NAME}" \
  .

echo ""
echo "✅ Agent deployed: $AGENT_NAME"
echo "   Verify gateway binding:"
echo "   bash scripts/verify_agent_binding.sh ${GOOGLE_CLOUD_PROJECT} ${GOOGLE_CLOUD_LOCATION}"
