#!/usr/bin/env bash

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This code is for PoC environment only.
# This demo code is not built for production workload.

# =============================================================================
# scripts/generate_agent_config.sh
#
# Reads Terraform outputs and generates a ready-to-source agent configuration
# file (agent.env) containing all values a consuming team needs to deploy
# their agent with correct Agent Gateway binding, OTEL, and identity config.
#
# Usage (from project root):
#   bash scripts/generate_agent_config.sh [--output agent.env]
#
# Output file is gitignored — it contains project-specific values.
# Source it in your deploy script:
#   source agent.env && bash scripts/deploy_my_agent.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( dirname "$SCRIPT_DIR" )"
# Optional: pass a custom output path as first arg. Default: <project_root>/agent.env
OUTPUT_PATH="${1:-${PROJECT_ROOT}/agent.env}"

cd "$PROJECT_ROOT"

echo "▶ Reading Terraform outputs..."

# Read all outputs at once
TF_OUTPUTS=$(terraform output -json 2>/dev/null) || {
  echo "❌ terraform output failed. Run 'terraform apply' first."
  exit 1
}

extract() {
  # Returns the value for a terraform output key, or empty string if not found.
  # NOTE: always exits 0 — use explicit empty-string check for fallback logic.
  echo "$TF_OUTPUTS" | python3 -c "
import json, sys
data = json.load(sys.stdin)
key = '$1'
val = data.get(key, {}).get('value', '')
print(val if val is not None else '')
"
}

# ── Read project identity ────────────────────────────────────────────────────
# project_id is a TF variable (not an output), so extract() returns empty.
# Fall through to terraform.tfvars grep, then gcloud config.
PROJECT_ID=$(extract project_id)
if [[ -z "$PROJECT_ID" ]]; then
  PROJECT_ID=$(grep -oP '^project_id\s*=\s*"\K[^"]+' terraform.tfvars 2>/dev/null || true)
fi
if [[ -z "$PROJECT_ID" ]]; then
  PROJECT_ID=$(gcloud config get-value project 2>/dev/null || true)
fi
if [[ -z "$PROJECT_ID" ]]; then
  echo "❌ Could not determine PROJECT_ID. Set it in terraform.tfvars or run: gcloud config set project YOUR_PROJECT_ID"
  exit 1
fi

REGION=$(grep -oP '^region\s*=\s*"\K[^"]+' terraform.tfvars 2>/dev/null || echo "us-east1")
LOCATION=$(grep -oP '^location\s*=\s*"\K[^"]+' terraform.tfvars 2>/dev/null || echo "$REGION")
PREFIX=$(grep -oP '^prefix\s*=\s*"\K[^"]+' terraform.tfvars 2>/dev/null || echo "")

INGRESS_GATEWAY=$(extract ingress_gateway_name)
EGRESS_GATEWAY=$(extract egress_gateway_name)
PROJECT_NUMBER=$(extract project_number)
MA_TEMPLATE=$(extract model_armor_template_id)

# Validate critical outputs were produced by terraform apply
if [[ -z "$INGRESS_GATEWAY" || -z "$EGRESS_GATEWAY" ]]; then
  echo "❌ Gateway outputs are empty. Run 'terraform apply' first."
  echo "   Expected outputs: ingress_gateway_name, egress_gateway_name"
  exit 1
fi
if [[ -z "$PROJECT_NUMBER" ]]; then
  echo "❌ project_number output is empty. Run 'terraform apply' first."
  exit 1
fi

# Derive Artifact Registry URL from project
AR_REGION="${REGION}"
AR_PROJECT="${PROJECT_ID}"
AR_REPO="agw-python-packages"
AR_URL="https://${AR_REGION}-python.pkg.dev/${AR_PROJECT}/${AR_REPO}/simple/"

echo "▶ Writing agent configuration to: $OUTPUT_PATH"

cat > "$OUTPUT_PATH" << EOF
# =============================================================================
# Agent Gateway — Agent Configuration
# Auto-generated by scripts/generate_agent_config.sh
# DO NOT commit this file — it contains project-specific values.
# Source this file before running your agent deploy script:
#   source agent.env && bash scripts/deploy_my_agent.sh
# =============================================================================

# ── GCP Project Identity ────────────────────────────────────────────────────
export GOOGLE_CLOUD_PROJECT="${PROJECT_ID}"
export GOOGLE_CLOUD_LOCATION="${LOCATION}"
export GOOGLE_CLOUD_REGION="${REGION}"
export PROJECT_NUMBER="${PROJECT_NUMBER}"

# ── Agent Gateway (inject these into agentGatewayConfig via .pth patch) ─────
# Used by: scripts/patch_sdk_for_rest_create.py
# These are the resource paths for the ingress and egress Agent Gateways.
export AGENT_GATEWAY_INGRESS="${INGRESS_GATEWAY}"
export AGENT_GATEWAY_EGRESS="${EGRESS_GATEWAY}"

# ── Artifact Registry — SDK source ─────────────────────────────────────────
# Add this as --extra-index-url in requirements.txt
# pip install --extra-index-url \$AR_PYTHON_INDEX gateway-agent-sdk==1.0.0
export AR_PYTHON_INDEX="${AR_URL}"
export AR_PROJECT="${AR_PROJECT}"
export AR_REGION="${AR_REGION}"
export AR_REPO="${AR_REPO}"

# ── Model Armor ─────────────────────────────────────────────────────────────
# Model Armor template used for prompt screening (security-high)
export MODEL_ARMOR_TEMPLATE="${MA_TEMPLATE}"

# ── OTEL Telemetry ──────────────────────────────────────────────────────────
# OTEL is AUTO-CONFIGURED by the GatewayAgent SDK via after_model_callback.
# The SDK emits llm_usage structured logs to Cloud Logging automatically.
# No manual OTEL setup needed — the SDK handles:
#   - Trace export to telemetry.googleapis.com/v1/traces
#   - Structured jsonPayload for agent observability dashboards
#   - Token counting (prompt_tokens, candidates_tokens, total_tokens)
#
# REQUIREMENT: 'telemetry.googleapis.com' must be in allowed_egress_hosts
# in terraform.tfvars — otherwise OTEL BatchSpanProcessor crashes Thread-2.
# See KNOWN_ISSUES.md #007.
export OTEL_EXPORTER_OTLP_ENDPOINT="https://telemetry.googleapis.com"
export OTEL_RESOURCE_ATTRIBUTES="gcp.project.id=${PROJECT_ID},deployment.region=${REGION}"

# ── SDK Version Pins ────────────────────────────────────────────────────────
# CRITICAL: Do NOT change these. See KNOWN_ISSUES.md #008.
export GATEWAY_AGENT_SDK_VERSION="1.0.0"
export GOOGLE_ADK_VERSION="1.31.1"
export GOOGLE_CLOUD_AIPLATFORM_VERSION="1.149.0"

# ── Prefix ─────────────────────────────────────────────────────────────────
export RESOURCE_PREFIX="${PREFIX}"

EOF

echo ""
echo "✅ Configuration written to: $OUTPUT_PATH"
echo ""
echo "Next steps:"
echo "  1. source agent.env"
echo "  2. Update agents/my-agent/requirements.txt:"
echo "       --extra-index-url \$AR_PYTHON_INDEX"
echo "       gateway-agent-sdk==\$GATEWAY_AGENT_SDK_VERSION"
echo "  3. Run your agent deploy script (it will read these env vars)"
echo ""
echo "Summary:"
echo "  Project     : ${PROJECT_ID} (${PROJECT_NUMBER})"
echo "  Region      : ${REGION}"
echo "  Ingress GW  : ${INGRESS_GATEWAY}"
echo "  Egress GW   : ${EGRESS_GATEWAY}"
echo "  AR Index    : ${AR_URL}"
